### ISSUE TITLE
Handle GitHub's tricky site loading behavior better

### ISSUE THREAD

**Issue by thieman** [thieman/github-selfies#15]
This flow almost always works:

1. Click on Pull Requests in the right bar
2. Click on New pull request, go from there

This doesn't:

1. Click on green shortcut button on the repo home page, middle-ish left
2. Click on a branch, keep going but script never fires

Instead of relying on Chrome to load us on certain paths, we should instead load on every GitHub page load and then fire relevant parts of the extension when we detect that the URL is a match.

**Comment by bhollis** [comment]
I have this working on my own local refactoring branch. :-)

**Comment by thieman** [comment]
Are you a wizard
