### ISSUE TITLE
Firefox extension is broken/abandoned

### ISSUE THREAD

**Issue by LucasMetal** [thieman/github-selfies#66]
Hi!

Very fun idea! 

Unluckily it doesn't seem to be working anymore right now in GitHub for my version of Firefox (I'm on the beta channel).
Am I the only one?

Thanks!

**Comment by bhollis** [comment]
Might need the same fixes as I've made for #68. I'll take a look at that if my PR gets merged.

**Comment by thieman** [comment]
The Firefox version is unfortunately abandoned following a lack of interest. I don't actively maintain the project any more, but there are enough Chrome users (like Ben here) using it and contributing fixes that the project's still alive. I think the Firefox version peaked at about 100 downloads so it just hasn't had the same support.

I've changed the Readme to reflect this, sorry for the confusion. If you or anybody else wants to port the current version of the Chrome extension into the Firefox part of the repo, I'd gladly merge it and reupload. Until then, we can keep this issue open to track Firefox support.

**Comment by bhollis** [comment]
Travis,

I'll see if I can't revive the FF plugin today. :-)

-Ben

**Comment by bhollis** [comment]
@thieman, quick question - were you using `cfx` or `jpm` to package the FF extension?

**Comment by thieman** [comment]
I see a `jetpack` tag on the project in the developer hub, which makes me think I probably used `jpm`.

**Comment by bhollis** [comment]
[![selfie-0](http://i.imgur.com/Dy7Gkzu.png)](https://github.com/thieman/github-selfies/)

This is the face I make when I have to deal with the Firefox Addon SDK (posted from Firefox, obviously :wink:)

**Comment by bhollis** [comment]
[![selfie-0](http://i.imgur.com/eD4a1mr.gif)](https://github.com/thieman/github-selfies/)
This is how I feel after another hour of wrestling with `nsIHttpChannel`. (Also posted from Firefox)

**Comment by bhollis** [comment]
Testing...

**Comment by bhollis** [comment]
More testing...

**Comment by LucasMetal** [comment]
haha cool!!
Thanks for the effort guys!! :)

**Comment by bhollis** [comment]
[![selfie-0](http://i.imgur.com/KXQlyh8.gif)](https://github.com/thieman/github-selfies/)

**Comment by thieman** [comment]
![](https://camo.githubusercontent.com/5fb829021cf01ef4b203065da9a9661099060de9/687474703a2f2f692e696d6775722e636f6d2f65443461316d722e676966)

**Comment by bhollis** [comment]
This should be resolved by #69 now.
