### ISSUE TITLE
Use github's image storage?

### ISSUE THREAD

**Issue by benjaminhollissc** [thieman/github-selfies#67]
Now that GitHub allows attaching files to issues directly (githubusercontent.com), it'd be cool if this extension could optionally use that instead of imgur. Thanks!

**Comment by thieman** [comment]
How exactly do you use that API? I was searching around and couldn't find anything on it.

**Comment by bhollis** [comment]
I reverse-engineered it, and it's pretty straightforward - you POST to a GitHub API that gives you some S3 credentials, then use that to store the file, then ping them again to report success.

Unfortunately, it looks like the policy they use leaves the content publicly readable (but with a hard-to-guess URL) which is not really any better than Imgur. So my original reason for wanting this (privacy) doesn't matter.

**Comment by bhollis** [comment]
You can close this.

**Comment by thieman** [comment]
:bear:

**Comment by corneadoug** [comment]
I think that base64 images could be an option if this PR is merged:
https://github.com/jch/html-pipeline/pull/227
