### ISSUE TITLE
Slack doesn't show selfies in previews because it's a link

### ISSUE THREAD

**Issue by thieman** [thieman/github-selfies#75]
From a reviewer in the Chrome store: "Good extension but it needs to just put a plain image and not make the image a link. The link causes the image not to show up in slack and that's just unacceptable :D. Maybe just append a link to the extension after the image?"

Wondering if there's some metadata we can throw somewhere to make Slack happy again.

**Comment by jcox92** [comment]
I think that was my feedback. Here's what it looks like in Slack:
![image](https://cloud.githubusercontent.com/assets/844493/13989457/da04cdd0-f0e6-11e5-973a-d08baa3a16f8.png)

I always just manually edit the markdown to exclude the link portion, which works fine. Maybe there's a different way to accomplish a link back to your repo?

**Comment by jcox92** [comment]
Submitted a PR for a possible alternative: https://github.com/thieman/github-selfies/pull/77

**Comment by thieman** [comment]
Merged #77.
