### ISSUE TITLE
Issue uploading selfie

### ISSUE THREAD

**Issue by lastcoolnameleft** [thieman/github-selfies#81]
I received the following error after taking a photo selfie:

Selfie URL: https://github.com/lastcoolnameleft/3d-dc/pull/1
Browser: Google Chrome: Version 51.0.2704.84 (64-bit)
Version: GitHub Selfies 2.0.2 (downloaded from Chrome Store)

FYI, this works for me in Firefox

This is the error that appears in the Chrome Console window.  Let me know if you need any other information to reproduce.

Refused to connect to 'https://api.imgur.com/3/upload' because it violates the following Content Security Policy directive: "connect-src 'self' uploads.github.com status.github.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com wss://live.github.com".

1:1 XMLHttpRequest cannot load https://api.imgur.com/3/upload. Failed to start loading.
selfie-base.js:347 Error uploading selfie Objectabort: (e)always: ()complete: ()done: ()error: ()fail: ()getAllResponseHeaders: ()getResponseHeader: (e)overrideMimeType: (e)pipe: ()progress: ()promise: (e)readyState: 0responseText: ""setRequestHeader: (e,t)state: ()status: 0statusCode: (e)statusText: "error"success: ()then: ()__proto__: ObjectuploadSelfie @ selfie-base.js:347
frameworks-7162bee….js:5 XHR finished loading: GET "https://github.com/lastcoolnameleft/3d-dc/issues/1/show_partial?partial=issues%2Fsidebar%2Flabels_menu_content".send @ frameworks-7162bee….js:5ajax @ frameworks-7162bee….js:4a @ frameworks-7162bee….js:10handle @ frameworks-7162bee….js:4dispatch @ frameworks-7162bee….js:4r.default.event.dispatch @ frameworks-7162bee….js:7r.default.event.dispatch @ frameworks-7162bee….js:7r.default.event.dispatch @ frameworks-7162bee….js:7v.handle @ frameworks-7162bee….js:3

**Comment by thieman** [comment]
This looks related to #80 which we generously already have a PR for, just need to find the time to review it. Thanks for the report! I'll ping this issue once #80 is released so you can confirm whether that fixed it for you.

**Comment by lastcoolnameleft** [comment]
You are fighting the good fight.  Many blessings upon you and yours.

**Comment by thieman** [comment]
Version 2.0.3 with the fix should be live in the Chrome store in the next couple of minutes. Please re-open if you're still having issues.

**Comment by SeanKilleen** [comment]
Works for me again -- thanks!

![selfie-1](http://i.imgur.com/9CQ5J1s.png)
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)
