### ISSUE TITLE
Issue uploading selfie

### ISSUE THREAD

**Issue by kieut** [thieman/github-selfies#87]
I haven't been able to pollute my PRs with github selfies ☹️ . This is similar to: https://github.com/thieman/github-selfies/issues/81

Browser: Google Chrome: Version 58.0.3029.110 (Official Build) (64-bit)
Version: GitHub Selfies 2.0.3 (downloaded from Chrome Store)

This is the error that appears in the Chrome Console window when I try to take a photo selfie.

Refused to connect to 'https://api.imgur.com/3/upload' because it violates the following Content Security Policy directive: "connect-src 'self' uploads.github.com status.github.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-user-asset-79cafe.s3.amazonaws.com wss://live.github.com".

**Comment by jessmartin** [comment]
SIMILAR! DO WANT POLLUTION! 💩

**Comment by xeviknal** [comment]
Bad news, github blocks all ajax request outside their services/providers: https://github.com/blog/1477-content-security-policy

Which would be the approaches to fix this? 
Who is up for telling github to add imgur to `connect-src` in CSP? :+1:  or :-1:

**Comment by thieman** [comment]
Fixed by #91.
